imports = [
  "language.go"
]

[devshell]
# This is the name of your environment. It should usually map to the project
# name.
name = "devshell"

# Message Of The Day (MOTD) is displayed when entering the environment with an
# interactive shell. By default it will show the project name.
#
# motd = ""

# Add packages from nixpkgs here. Use `nix search nixpkgs <term>` to find the
# package that you need.
#
# NOTE: don't forget to put commas between items! :)
packages = [
  "diffutils", # used by golangci-lint
  "goreleaser",
  "mdbook",
  "mdsh",
  "webfs",
  "hyperfine",
]

# Expose all the dependencies from a package to the environment.
packagesFrom = [
  "direnv"
]

# Declare commands that are available in the environment.
[commands.hello]
help = "prints hello"
command = "echo hello"

[commands.nixpkgs-fmt]
category = "formatters"

[commands.go]

[commands.hub]
help = "github utility"
category = "utilities"

[commands.golangci-lint]
help = "golang linter"
category = "linters"

[env]
testStr = "foo"
testInt = 123
testBool = true

[env.ZZZTEST_ENV]
value = "${GO111MODULE:?}"
eval = true
[env.AAATEST_ENV]
value = "${GO111MODULE:?}"
eval = true
[env.AAATEST_PRJDATA]
value = "${PRJ_DATA_DIR:-${PRJ_ROOT}}"
eval = true
