# https://numtide.github.io/devshell
# https://numtide.github.io/devshell/getting_started.html
[commands.hello]
package = "hello"

[commands.go]
package = "go"

[commands.node]
package = "nodejs_20"

[commands.python]
package = "python311"

[env.GO111MODULE]
value = "on"

[devshell]
packages = [
  "postgresql_15",
  "memcached",
]

[commands.initPostgres]
help = "Initialize the Postgres database"
command = """\
  initdb pgdata; \
  chmod -R 700 pgdata; \
  echo -e "Use the devshell command 'database:start'"
  """

[serviceGroups.database]
description = "Runs a database in the background"
[serviceGroups.database.services.postgres]
command = "postgres -D ./pgdata"
[serviceGroups.database.services.memcached]
command = "memcached"
