[book]
authors = ["zimbatm", "KaiSforza"]
language = "en"
multilingual = false
src = "src"
title = "devshell"

[output.html]
# Show github links in top bar
git-repository-url = "https://github.com/KaiSforza/devshell"
edit-url-template = "https://github.com/KaiSforza/devshell/edit/attrs/docs/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
fold.enable = true
