name: Nix
on:
  push:
    branches:
      - attrs
      - staging
      - trying
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: kaisforza
      - run: |
          export PRJ_ROOT=$PWD
          $(./shell.nix)/entrypoint --pure bash -c "echo OK"
      - run: nix-shell --run "echo OK"
      - run: nix-build
  flakes:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: kaisforza
      - run: nix flake check
      - name: Run devshell entry sanity checks
        run: |
          nix develop -c echo OK
          for tmpl in ./templates/*; do
            if ! [ -d "$tmpl" ]; then
              continue
            fi
            nix develop --override-input devshell . "$tmpl" -c echo OK
          done
      - name: Run nix flake archive
        run: nix flake archive
  docs:
    strategy:
      matrix:
        os: [ ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: kaisforza
      - run: |
          nix-build -A docs
          cp -r "$(readlink ./result)" book
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/attrs'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
